name: CI Build

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Nuget Package Dependencies
        run: dotnet restore agile-team-tools.sln

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore 

      - name: Run Unit Tests
        run: dotnet test --no-restore --verbosity normal